#!/bin/bash

#-------------------------------------------------------------------------------
#   Name:           configuration.sh                                            
#                                                                               
#   Purpose:        Create the .pro and Makefile files for the known main       
#                   programs.                                                   
#                                                                               
#   Note:           This file is automatically generated by the make.qt.config  
#                   tool.  You should not modify this file by hand.             
#                                                                               
#   make.qt.config                                                              
#       -d../qt                                                                 
#       -d../qt/images                                                          
#       -I../common                                                             
#       -q../qt/datr                                                            
#       -qtwidgets                                                              
#       --qmake=qmake-qt4                                                       
#       -f-std=c++11                                                            
#                                                                               
#   Version:                                                                    
#       2020-10-05    MQC       Generated by make.qt.config V 1.0.0             
#                                                                               
#-------------------------------------------------------------------------------

../tools/makepro                                                            \
    -m../qt/fileapp.cpp                                                     \
    -d../qt                                                                 \
    -d../qt/images                                                          \
    -I../common                                                             \
    -f-std=c++11                                                            \
    -qtwidgets                                                              \
    -q../qt/datr                                                            \
    >fileapp.pro


qmake-qt4 -o Makefile-fileapp fileapp.pro

