#!/bin/bash

#-------------------------------------------------------------------------------
#                                                                               
#   Name: makeconfig                                                            
#                                                                               
#   Purpose:    Create the configure.sh file which will create the .pro files   
#               and Makefiles.                                                  
#                                                                               
#               This script should be executed everytime that a new main.cpp is 
#               created.                                                        
#                                                                               
#   Note:       This file is created and maintained by hand.                    
#                                                                               
#   Note:       We would prefer to use Qt v5, but some of our developers are    
#               trapped at Qt v4 (and they don't have control over their        
#               development environment).                                       
#                                                                               
#   @version    2016-04-04  DHF     File creation.                              
#                                                                               
#   @version    2017-08-22  DHF     Added libcrypto.so                          
#                                                                               
#-------------------------------------------------------------------------------

OUTPUT_DIR=../../../datr-non-cm/linux/
BOOST=${OUTPUT_DIR}boost/
BOOST_LIB=${BOOST}lib/

../tools/make.qt.config                                     \
    -d../qt                                                 \
    -d../qt/images                                          \
    -I../common                                             \
    -q../qt/datr                                            \
    -qtwidgets                                              \
    --qmake=qmake-qt4                                       \
    -f-std=c++11


chmod u+x build configure.sh

